version: '3.9'
services:
  app:
    build: .
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./src:/amazon-transcribe-streaming-sdk/src
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    tty: true
    ports:
      - 5500:3000
    command: python /amazon-transcribe-streaming-sdk/src/simple_mic_PortAudio.py
